from quandl.learning_setups.aapl_2004_basic_net_raw_set_provider_setup \
    import aapl_2004_basic_net_raw_set_provider_setup
from quandl.learning_setups.aapl_2004_basic_net_difference_set_provider_setup \
    import aapl_2004_basic_net_difference_set_provider_setup
from quandl.learning_setups.aapl_2004_basic_net_relative_difference_set_provider_setup \
    import aapl_2004_basic_net_relative_difference_set_provider_setup
from quandl.learning_setups.aapl_2004_lstm_net_relative_difference_set_provider_setup \
    import aapl_2004_lstm_net_relative_difference_set_provider_setup


#aapl_2004_basic_net_raw_set_provider_setup().fit()
#aapl_2004_basic_net_difference_set_provider_setup().fit()
#aapl_2004_basic_net_relative_difference_set_provider_setup().fit()
aapl_2004_lstm_net_relative_difference_set_provider_setup().fit()

